version: '3.8'

services:
  testbot-app:
    build: ./
    command: ./wait-for-postgres.sh db ./bottest
    ports:
      - 8081:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
      - TG_TOKEN=TOKEN


  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432
